algoritmo "aula 1 laço de repetição"
// Função :
// Autor :
// Data : 30/07/2019
// Seção de Declarações 
var
numero:inteiro
inicio
escreval("-------LAÇO ENQUANTO-------")
numero<-1
 enquanto (numero<=10) faca
 escreval(numero)
  numero<-numero+1
fimenquanto

escreval("-------LAÇO PARA-------")
numero<-1
 para numero de 1 ate 10 faca
 escreval(numero)
fimpara
 
escreval("-------LAÇO REPITA-------")
numero<-1
 repita
  escreval(numero)
  numero<-numero+1
  ate(numero>=10)

fimalgoritmo
