algoritmo "semnome"
// Função :
// Autor :
// Data : 30/07/2019
// Seção de Declarações 
var
x,numero,positivo,negativo:inteiro
inicio
x<-0
positivo<-0
negativo<-0
para x de 1 ate 20 faca
 escreval("Digite um valor")
 leia (numero)
  se(numero>0)entao
  positivo<-positivo+num
  
  senao
  negativo<-negativo+1
  
fimse
fimpara
 escreval("NUMERO DE NUMEROS NEGATIVOS É :",negativo)
 escreval("A SOMA DOS NUMEROS POSITIVOS É :",positivo)
fimalgoritmo

