algoritmo "semnome"
// Função :
// Autor :
// Data : 20/08/2019
// Seção de Declarações 
var
cont,num,fatori:inteiro
inicio
fatori<-1
escreval("---------------------------------------------")
escreval("Digite um numero para calcularmos a Fatoração")
 escreval("---------------------------------------------")
leia(num)
 para cont de 1 ate num faca
 fatori<-fatori*cont
 escreval(num, "X", fatori)
 num<-num-1
 
 fimpara
 escreval("---------------------------------------------")
 escreval("a Fatoração deu: ", fatori)
 escreval("---------------------------------------------")
 
fimalgoritmo
