algoritmo "semnome"
// Função :
// Autor :
// Data : 13/08/2019
// Seção de Declarações 
var
soma,num,resposta:Inteiro
inicio
soma<-0
repita
escreval("-------------------------------")
 escreval("digite um numero inteiro")
 escreval("digite 0 Para Sair")
escreval("-------------------------------")
leia(num)
 soma<-soma+num
ate (num=0)
escreval("-------------------------------")
escreval("A soma dos numeros é:",soma)
escreval("-------------------------------")

fimalgoritmo
